// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trace-sampling-manager.proto

package trace_sampling_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Host struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d6cc870899719bb, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type HostsToTraceRequest struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostsToTraceRequest) Reset()         { *m = HostsToTraceRequest{} }
func (m *HostsToTraceRequest) String() string { return proto.CompactTextString(m) }
func (*HostsToTraceRequest) ProtoMessage()    {}
func (*HostsToTraceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d6cc870899719bb, []int{1}
}

func (m *HostsToTraceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostsToTraceRequest.Unmarshal(m, b)
}
func (m *HostsToTraceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostsToTraceRequest.Marshal(b, m, deterministic)
}
func (m *HostsToTraceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostsToTraceRequest.Merge(m, src)
}
func (m *HostsToTraceRequest) XXX_Size() int {
	return xxx_messageInfo_HostsToTraceRequest.Size(m)
}
func (m *HostsToTraceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostsToTraceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostsToTraceRequest proto.InternalMessageInfo

func (m *HostsToTraceRequest) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type GetHostsToTraceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostsToTraceRequest) Reset()         { *m = GetHostsToTraceRequest{} }
func (m *GetHostsToTraceRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostsToTraceRequest) ProtoMessage()    {}
func (*GetHostsToTraceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d6cc870899719bb, []int{2}
}

func (m *GetHostsToTraceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostsToTraceRequest.Unmarshal(m, b)
}
func (m *GetHostsToTraceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostsToTraceRequest.Marshal(b, m, deterministic)
}
func (m *GetHostsToTraceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostsToTraceRequest.Merge(m, src)
}
func (m *GetHostsToTraceRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostsToTraceRequest.Size(m)
}
func (m *GetHostsToTraceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostsToTraceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostsToTraceRequest proto.InternalMessageInfo

type GetHostsToTraceResponse struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostsToTraceResponse) Reset()         { *m = GetHostsToTraceResponse{} }
func (m *GetHostsToTraceResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostsToTraceResponse) ProtoMessage()    {}
func (*GetHostsToTraceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d6cc870899719bb, []int{3}
}

func (m *GetHostsToTraceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostsToTraceResponse.Unmarshal(m, b)
}
func (m *GetHostsToTraceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostsToTraceResponse.Marshal(b, m, deterministic)
}
func (m *GetHostsToTraceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostsToTraceResponse.Merge(m, src)
}
func (m *GetHostsToTraceResponse) XXX_Size() int {
	return xxx_messageInfo_GetHostsToTraceResponse.Size(m)
}
func (m *GetHostsToTraceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostsToTraceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostsToTraceResponse proto.InternalMessageInfo

func (m *GetHostsToTraceResponse) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d6cc870899719bb, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Host)(nil), "trace_sampling_manager.Host")
	proto.RegisterType((*HostsToTraceRequest)(nil), "trace_sampling_manager.HostsToTraceRequest")
	proto.RegisterType((*GetHostsToTraceRequest)(nil), "trace_sampling_manager.GetHostsToTraceRequest")
	proto.RegisterType((*GetHostsToTraceResponse)(nil), "trace_sampling_manager.GetHostsToTraceResponse")
	proto.RegisterType((*Empty)(nil), "trace_sampling_manager.Empty")
}

func init() {
	proto.RegisterFile("trace-sampling-manager.proto", fileDescriptor_4d6cc870899719bb)
}

var fileDescriptor_4d6cc870899719bb = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x29, 0x4a, 0x4c,
	0x4e, 0xd5, 0x2d, 0x4e, 0xcc, 0x2d, 0xc8, 0xc9, 0xcc, 0x4b, 0xd7, 0xcd, 0x4d, 0xcc, 0x4b, 0x4c,
	0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x03, 0xcb, 0xc6, 0xc3, 0x64, 0xe3,
	0xa1, 0xb2, 0x4a, 0x66, 0x5c, 0x2c, 0x1e, 0xf9, 0xc5, 0x25, 0x42, 0x52, 0x5c, 0x1c, 0x19, 0xf9,
	0xc5, 0x25, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90,
	0x10, 0x17, 0x4b, 0x41, 0x7e, 0x51, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0xad,
	0xe4, 0xc9, 0x25, 0x0c, 0xd2, 0x57, 0x1c, 0x92, 0x1f, 0x02, 0x32, 0x38, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x44, 0xc8, 0x88, 0x8b, 0x15, 0xa4, 0xad, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x46, 0x0f, 0xbb, 0xb5, 0x7a, 0x20, 0xbd, 0x41, 0x10, 0xa5, 0x4a, 0x12, 0x5c, 0x62, 0xee,
	0xa9, 0x25, 0x58, 0x4c, 0x53, 0xf2, 0xe5, 0x12, 0xc7, 0x90, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x25, 0xcb, 0x22, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0xa3, 0xb7, 0x8c, 0x5c, 0x22,
	0x60, 0xe3, 0x82, 0xa1, 0xca, 0x7d, 0x21, 0xaa, 0x85, 0xe2, 0xb9, 0xf8, 0x83, 0x51, 0x2d, 0x14,
	0xd2, 0xc6, 0x67, 0x32, 0x9a, 0x83, 0xa5, 0x64, 0x71, 0x29, 0x06, 0xdb, 0xab, 0xc4, 0x20, 0x54,
	0xc2, 0xc5, 0x8f, 0xe6, 0x23, 0x21, 0x3d, 0x5c, 0x7a, 0xb0, 0x07, 0x8a, 0x94, 0x3e, 0xd1, 0xea,
	0x21, 0x41, 0xa5, 0xc4, 0xe0, 0xa4, 0x1c, 0xa5, 0x98, 0x5e, 0x54, 0x90, 0x1c, 0x0f, 0x4e, 0x0a,
	0xfa, 0xd8, 0xb5, 0x27, 0xb1, 0x81, 0x65, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0xfc,
	0x8b, 0x2d, 0x48, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TraceSamplingManagerClient is the client API for TraceSamplingManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraceSamplingManagerClient interface {
	SetHostsToTrace(ctx context.Context, in *HostsToTraceRequest, opts ...grpc.CallOption) (*Empty, error)
	GetHostsToTrace(ctx context.Context, in *GetHostsToTraceRequest, opts ...grpc.CallOption) (*GetHostsToTraceResponse, error)
}

type traceSamplingManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceSamplingManagerClient(cc grpc.ClientConnInterface) TraceSamplingManagerClient {
	return &traceSamplingManagerClient{cc}
}

func (c *traceSamplingManagerClient) SetHostsToTrace(ctx context.Context, in *HostsToTraceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/trace_sampling_manager.TraceSamplingManager/SetHostsToTrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceSamplingManagerClient) GetHostsToTrace(ctx context.Context, in *GetHostsToTraceRequest, opts ...grpc.CallOption) (*GetHostsToTraceResponse, error) {
	out := new(GetHostsToTraceResponse)
	err := c.cc.Invoke(ctx, "/trace_sampling_manager.TraceSamplingManager/GetHostsToTrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceSamplingManagerServer is the server API for TraceSamplingManager service.
type TraceSamplingManagerServer interface {
	SetHostsToTrace(context.Context, *HostsToTraceRequest) (*Empty, error)
	GetHostsToTrace(context.Context, *GetHostsToTraceRequest) (*GetHostsToTraceResponse, error)
}

// UnimplementedTraceSamplingManagerServer can be embedded to have forward compatible implementations.
type UnimplementedTraceSamplingManagerServer struct {
}

func (*UnimplementedTraceSamplingManagerServer) SetHostsToTrace(ctx context.Context, req *HostsToTraceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHostsToTrace not implemented")
}
func (*UnimplementedTraceSamplingManagerServer) GetHostsToTrace(ctx context.Context, req *GetHostsToTraceRequest) (*GetHostsToTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostsToTrace not implemented")
}

func RegisterTraceSamplingManagerServer(s *grpc.Server, srv TraceSamplingManagerServer) {
	s.RegisterService(&_TraceSamplingManager_serviceDesc, srv)
}

func _TraceSamplingManager_SetHostsToTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsToTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceSamplingManagerServer).SetHostsToTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trace_sampling_manager.TraceSamplingManager/SetHostsToTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceSamplingManagerServer).SetHostsToTrace(ctx, req.(*HostsToTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceSamplingManager_GetHostsToTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostsToTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceSamplingManagerServer).GetHostsToTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trace_sampling_manager.TraceSamplingManager/GetHostsToTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceSamplingManagerServer).GetHostsToTrace(ctx, req.(*GetHostsToTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TraceSamplingManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trace_sampling_manager.TraceSamplingManager",
	HandlerType: (*TraceSamplingManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetHostsToTrace",
			Handler:    _TraceSamplingManager_SetHostsToTrace_Handler,
		},
		{
			MethodName: "GetHostsToTrace",
			Handler:    _TraceSamplingManager_GetHostsToTrace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trace-sampling-manager.proto",
}
